os: osx
osx_image: xcode8.3
sudo: required

language: cpp

compiler:
  - gcc

before_install:
  - brew update
  - brew install jq
  - brew install cartr/qt4/qt@4
  - brew install asciidoctor

before_script:
  - git clone --depth 1 https://github.com/openscap/openscap.git -b master
  - pushd openscap/build
  - cmake -DENABLE_PROBES=FALSE ../
  - make -j 4
  - make install
  - popd

script:
  - ./build-for-osx.sh
  - wget `curl -s https://api.github.com/repos/openscap/scap-security-guide/releases/latest?access_token=$GITHUB_TOKEN | jq -r ".assets[] | select(.name | test(\"(scap-security-guide-[0-9].[0-9].[0-9]*).zip\")) | .browser_download_url"` -O ssg.zip
  - mkdir -p `pwd`/scap-workbench.app/Contents/Resources/ssg/ && unzip ssg.zip -d `pwd`/scap-workbench.app/Contents/Resources/ssg/
  - cd build-osx && sh osx-create-dmg.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: scap-workbench-$TRAVIS_TAG.dmg
  skip_cleanup: true
  on:
    tags: true
